import { renderFirstMessage } from './lib/first-message-renderer';
import * as Sentry from '@sentry/node';
import type { SupabaseClient } from '@supabase/supabase-js';

function getApiKey(): string {
  const key = process.env.ELEVENLABS_API_KEY;
  if (!key) throw new Error('ELEVENLABS_API_KEY environment variable is required but not set');
  return key;
}

/**
 * Operator-transfer config for the ElevenLabs `transfer_to_number` system
 * tool. Schema mirrors the OpenAPI types we read from api.elevenlabs.io
 * (TransferToNumberToolConfig-Input → PhoneNumberTransfer →
 * PhoneNumberTransferDestination). See agents.ts:buildTransferTool for
 * the JSON shape we ship.
 *
 * `waitMessageTemplate` and `warmMessageTemplate` are NOT static config
 * fields on the ElevenLabs side — `client_message` and `agent_message`
 * are runtime args the LLM produces when invoking the tool. We surface
 * them to the LLM via the tool's `description` so it generates the
 * runtime values from the customer's template. The route handler does
 * any {business_name} interpolation before passing them in.
 */
export type TransferConfig = {
  phoneNumber: string;        // E.164, validated at the route layer
  condition: string;          // natural-language WHEN-to-transfer text
  waitMessageTemplate?: string;
  warmMessageTemplate?: string;
};

const TRANSFER_TOOL_NAME = 'transfer_to_number';

/**
 * Build the tools-array entry for the transfer_to_number system tool.
 * Shape per ElevenLabs OpenAPI components.schemas.TransferToNumberToolConfig-Input
 * and PhoneNumberTransfer:
 *   {
 *     type: 'system',
 *     name: 'transfer_to_number',
 *     description: <hint to the LLM, includes the customer's wait/warm
 *                  message templates so the runtime client_message /
 *                  agent_message arguments respect their wording>,
 *     params: {
 *       system_tool_type: 'transfer_to_number',
 *       transfers: [{
 *         transfer_destination: { type: 'phone', phone_number: '+1...' },
 *         condition: '<when to transfer>',
 *         transfer_type: 'conference',
 *       }],
 *       enable_client_message: true,
 *     },
 *   }
 *
 * transfer_type: 'conference' is the warm-handoff default per
 * TransferTypeEnum (values: 'blind' | 'conference' | 'sip_refer'). Note:
 * the user spec mentioned 'conference_call' but the API enum is
 * 'conference' — using the canonical value.
 */
export function buildTransferTool(cfg: TransferConfig): unknown {
  const wait = (cfg.waitMessageTemplate || '').trim();
  const warm = (cfg.warmMessageTemplate || '').trim();
  // The runtime client_message / agent_message values are generated by
  // the LLM. Hint it via the tool description so the customer's
  // templates shape what gets said. Without these hints the LLM would
  // improvise generic phrasing.
  const descParts = ['Transfer the caller to a human operator when the condition is met.'];
  if (wait) descParts.push(`When transferring, use this as the message read to the CALLER (client_message): "${wait}"`);
  if (warm) descParts.push(`When transferring, use this as the message read to the OPERATOR who picks up (agent_message): "${warm}"`);
  return {
    type: 'system',
    name: TRANSFER_TOOL_NAME,
    description: descParts.join(' '),
    params: {
      system_tool_type: 'transfer_to_number',
      transfers: [
        {
          transfer_destination: {
            type: 'phone',
            phone_number: cfg.phoneNumber,
          },
          condition: cfg.condition,
          transfer_type: 'conference',
        },
      ],
      enable_client_message: true,
    },
  };
}

export async function createAgentForBusiness(opts: {
  businessId: string;
  businessName: string;
  systemPrompt: string;
  firstMessage?: string;
  language?: string;            // Phase 3l: ISO 639-1 code (en, es, fr, pt, zh, ar, …)
  languageDetection?: boolean;  // Phase 3l: enable for non-English so caller code-switching works
  transferConfig?: TransferConfig; // operator-transfer system tool
}): Promise<{ success: boolean; agentId?: string; error?: string }> {
  try {
    console.log('[Agents] Creating agent for:', opts.businessName, 'language:', opts.language || 'en');

    const agentConfig: any = {
      prompt: {
        prompt: opts.systemPrompt
      },
      // Defensive fallback: every production caller now passes a
      // disclosure-compliant firstMessage built via renderFirstMessage.
      // If a future caller forgets, we still emit a compliant greeting
      // instead of the legacy "Hello, thank you for calling…" template
      // that lacked the recording disclosure.
      first_message: opts.firstMessage || renderFirstMessage({ business_name: opts.businessName }),
      language: opts.language || 'en',
    };
    if (opts.languageDetection) {
      agentConfig.language_detection = true;
    }
    if (opts.transferConfig) {
      // Tools live under prompt.tools per the OpenAPI shape (the schema's
      // PromptAgentInputToolsItem_System variant). Stays alongside `prompt`
      // and `language_detection` on the agent.prompt object.
      agentConfig.prompt.tools = [buildTransferTool(opts.transferConfig)];
    }

    const response = await fetch('https://api.elevenlabs.io/v1/convai/agents/create', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'xi-api-key': getApiKey()
      },
      body: JSON.stringify({
        name: `Neverr - ${opts.businessName}`,
        conversation_config: {
          agent: agentConfig,
          tts: {
            voice_id: 'EXAVITQu4vr4xnSDxMaL'
          }
        }
      })
    });

    const data: any = await response.json();
    console.log('[Agents] ElevenLabs response:', JSON.stringify(data).substring(0, 200));

    if (data.agent_id) {
      console.log('[Agents] Agent created:', data.agent_id, 'for', opts.businessName);
      return { success: true, agentId: data.agent_id };
    }

    return { success: false, error: JSON.stringify(data) };
  } catch (err: any) {
    console.error('[Agents] Error creating agent:', err.message);
    return { success: false, error: err.message };
  }
}

export async function updateAgentPrompt(opts: {
  agentId: string;
  systemPrompt: string;
  firstMessage?: string;
  businessName?: string;
  languageDetection?: boolean;
}): Promise<{ success: boolean; error?: string }> {
  try {
    const agentConfig: any = {
      prompt: {
        prompt: opts.systemPrompt
      },
      first_message: opts.firstMessage
    };
    if (opts.languageDetection) {
      agentConfig.language_detection = true;
    }
    const response = await fetch(`https://api.elevenlabs.io/v1/convai/agents/${opts.agentId}`, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        'xi-api-key': getApiKey()
      },
      body: JSON.stringify({
        name: opts.businessName ? `Neverr - ${opts.businessName}` : undefined,
        conversation_config: {
          agent: agentConfig
        }
      })
    });

    const data = await response.json();
    if (response.ok) {
      console.log('[Agents] Agent updated:', opts.agentId);
      return { success: true };
    }
    return { success: false, error: JSON.stringify(data) };
  } catch (err: any) {
    return { success: false, error: err.message };
  }
}

export async function getAgent(agentId: string) {
  const response = await fetch(`https://api.elevenlabs.io/v1/convai/agents/${agentId}`, {
    headers: { 'xi-api-key': getApiKey() }
  });
  return response.json();
}

export async function deleteAgent(agentId: string): Promise<{ success: boolean; error?: string }> {
  try {
    const response = await fetch(`https://api.elevenlabs.io/v1/convai/agents/${agentId}`, {
      method: 'DELETE',
      headers: {
        'xi-api-key': getApiKey()
      }
    });

    if (response.ok || response.status === 404) {
      console.log('[Agents] Deleted agent:', agentId);
      return { success: true };
    }

    const errText = await response.text().catch(() => '');
    console.warn('[Agents] Delete failed:', response.status, errText.substring(0, 200));
    return { success: false, error: `HTTP ${response.status}` };
  } catch (err: any) {
    console.error('[Agents] Delete error:', err.message);
    return { success: false, error: err.message };
  }
}

/**
 * Idempotent sync of a business's operator-transfer config to its
 * ElevenLabs agent. Reads business_configs for `agent_id` +
 * `transfer_enabled` + the four transfer fields, then PATCHes the agent's
 * tools array:
 *
 *   transfer_enabled = false → strip any existing `transfer_to_number`
 *                              system tool from agent.prompt.tools
 *   transfer_enabled = true  → upsert the tool (replace existing entry
 *                              of the same name, or append if missing)
 *
 * Safe to call repeatedly. Failures are captured to Sentry and logged but
 * do NOT throw — the route handler that triggered this can still respond
 * 200 on the DB write; the customer's saved settings will resync via a
 * follow-up save if ElevenLabs was temporarily unreachable.
 *
 * Returns { success, error? } for the rare caller that wants to surface
 * the sync state (e.g. an admin tool showing prompt_sync_error).
 */
export async function updateAgentTransferConfig(
  supabase: SupabaseClient,
  businessId: string,
): Promise<{ success: boolean; error?: string }> {
  try {
    const { data: biz, error: readErr } = await supabase
      .from('business_configs')
      .select('agent_id, business_name, transfer_enabled, transfer_to_phone, transfer_conditions, transfer_wait_message, transfer_warm_message')
      .eq('business_id', businessId)
      .maybeSingle();
    if (readErr) {
      Sentry.captureMessage('update_agent_transfer_config_read_failed', {
        level: 'error',
        extra: { businessId, error: readErr.message },
      });
      return { success: false, error: readErr.message };
    }
    if (!biz) {
      return { success: false, error: 'business_not_found' };
    }
    const row = biz as {
      agent_id: string | null;
      business_name: string | null;
      transfer_enabled: boolean | null;
      transfer_to_phone: string | null;
      transfer_conditions: string | null;
      transfer_wait_message: string | null;
      transfer_warm_message: string | null;
    };
    if (!row.agent_id) {
      // No ElevenLabs agent yet (business hasn't completed onboarding).
      // Nothing to sync — settings are persisted in business_configs and
      // will be picked up when the agent is created.
      return { success: true };
    }

    // GET the agent so we can preserve any other tools that may exist
    // alongside transfer_to_number (none today, but defensive). The
    // ElevenLabs PATCH semantic on prompt.tools replaces the array
    // wholesale.
    const getRes = await fetch(`https://api.elevenlabs.io/v1/convai/agents/${row.agent_id}`, {
      headers: { 'xi-api-key': getApiKey() },
    });
    if (!getRes.ok) {
      const errText = await getRes.text().catch(() => '');
      Sentry.captureMessage('update_agent_transfer_config_get_failed', {
        level: 'error',
        extra: { businessId, agentId: row.agent_id, status: getRes.status, body: errText.slice(0, 500) },
      });
      return { success: false, error: `agent_get_http_${getRes.status}` };
    }
    const agent: any = await getRes.json();
    const existingTools: any[] = Array.isArray(agent?.conversation_config?.agent?.prompt?.tools)
      ? agent.conversation_config.agent.prompt.tools
      : [];
    // Belt-and-suspenders against an ElevenLabs PATCH wiping the system
    // prompt string when we only send prompt.tools. The OpenAPI shape
    // says nested merge SHOULD preserve sibling fields, but we hold the
    // current prompt text in hand from the GET above so the cost of
    // also echoing it back in the PATCH body is one extra string in
    // the JSON — and the upside is that a misunderstanding of the
    // merge semantic doesn't blow away the customer's system prompt.
    const currentPromptText: string | undefined =
      typeof agent?.conversation_config?.agent?.prompt?.prompt === "string"
        ? agent.conversation_config.agent.prompt.prompt
        : undefined;
    // Strip any existing transfer_to_number tool — we'll re-add it below
    // if transfer_enabled is true. Identifying by name OR
    // params.system_tool_type so renames don't leave dupes.
    const remainingTools = existingTools.filter((t: any) =>
      t?.name !== TRANSFER_TOOL_NAME && t?.params?.system_tool_type !== 'transfer_to_number',
    );

    let nextTools: any[] = remainingTools;
    if (row.transfer_enabled && row.transfer_to_phone && row.transfer_conditions) {
      // Server-side {business_name} interpolation on the messages — we
      // store the customer's template with the literal placeholder and
      // resolve it here so editing the business name later doesn't
      // require a re-save of the transfer template.
      const businessName = row.business_name || 'our team';
      const interpolate = (tpl: string | null) =>
        (tpl || '').replace(/\{business_name\}/g, businessName);
      nextTools = [
        ...remainingTools,
        buildTransferTool({
          phoneNumber: row.transfer_to_phone,
          condition: row.transfer_conditions,
          waitMessageTemplate: interpolate(row.transfer_wait_message),
          warmMessageTemplate: interpolate(row.transfer_warm_message),
        }),
      ];
    }

    const promptBody: any = { tools: nextTools };
    if (typeof currentPromptText === 'string') {
      promptBody.prompt = currentPromptText;
    }
    const patchRes = await fetch(`https://api.elevenlabs.io/v1/convai/agents/${row.agent_id}`, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        'xi-api-key': getApiKey(),
      },
      body: JSON.stringify({
        conversation_config: {
          agent: {
            prompt: promptBody,
          },
        },
      }),
    });
    if (!patchRes.ok) {
      const errText = await patchRes.text().catch(() => '');
      Sentry.captureMessage('update_agent_transfer_config_patch_failed', {
        level: 'error',
        extra: { businessId, agentId: row.agent_id, status: patchRes.status, body: errText.slice(0, 500), enabled: row.transfer_enabled },
      });
      return { success: false, error: `agent_patch_http_${patchRes.status}` };
    }
    console.log('[Agents] Transfer config synced:', businessId, 'enabled=', row.transfer_enabled, 'agent=', row.agent_id);
    return { success: true };
  } catch (err: any) {
    Sentry.captureException(err, { extra: { route: 'updateAgentTransferConfig', businessId } });
    return { success: false, error: err?.message || String(err) };
  }
}

export default { createAgentForBusiness, updateAgentPrompt, getAgent, deleteAgent, updateAgentTransferConfig, buildTransferTool };
